# Generated by Django 2.1.2 on 2019-08-25 05:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0002_student'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Student',
        ),
    ]
